name: Cargo Build & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "README.md"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "README.md"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain:
          - nightly-2022-11-03
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose
