name: Cargo Build & Test

env:
  rust_nightly: nightly-2023-01-10

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "README.md"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "README.md"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain: ${{ env.rust_nightly }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose
