name: Cargo Build & Test

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - ".github/workflows/*"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain:
          - nightly-2024-10-17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose
